services:
  nextjs:
    build:
      context: ./iusreact  # path to the Next.js app directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - iusapi
      - db
    networks:
      - app-network

  iusapi:
    build:
      context: ./iusapi  # path to the Node.js iusapi directory
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:secure@db:5432/db
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: ankane/pgvector:latest  # Use the pgvector image instead of plain postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secure
      POSTGRES_DB: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local

networks:
  app-network:
    driver: bridge
